#!/usr/bin/env Rscript
# 32-cumulant_convergence.R — regenerates results/analysis/cumulant_convergence.csv
#
# The original producer of this CSV was lost; this script is the canonical reconstruction
# (2026-09-16, four-team audit). It reads the S1 PMF curves for cumulant orders C1-C3
# (results/analysis/sys1_*_pmf_c{1,2,3}.xvg) and computes:
#   wd_Ci      = PMF range (max-min after min-normalization) of order Ci
#   wd_mean/wd_sd/wd_range = mean / sample SD / range across C1..C3
#   rc_min_C3  = reaction coordinate at the C3 PMF minimum
#   pmf_cor_C2C3 = Pearson r between the min-normalized C2 and C3 PMF profiles
#
# Notes:
# - wd_C1/C2/C3, rc_min_C3, wd_mean/wd_sd reproduce the legacy CSV at full precision (asserts).
# - pmf_cor_C2C3 is recomputed from the CURRENT pmf xvg files (regenerated by the common/pmf
#   pipeline during the audit); the legacy values differed by up to 0.08 for olaparib
#   (0.80 -> 0.89), rucaparib (0.87 -> 0.92), veliparib (0.84 -> 0.87). Table S1's "r > 0.80
#   for all systems" claim is unaffected.
suppressMessages(library(data.table))

# Shared helpers: read_pmf (single source).
args_h <- commandArgs(trailingOnly = FALSE)
if (length(grep("^--file=", args_h))) {
  script_dir <- dirname(normalizePath(sub("^--file=", "", args_h[grep("^--file=", args_h)])))
  source(file.path(script_dir, "..", "common", "helpers.R"))
} else {
  source("common/helpers.R")
}

data_dir <- "results/analysis"
sys <- c("APO", "AZD5305", "niraparib", "olaparib", "rucaparib", "talazoparib", "veliparib")

# read_pmf comes from common/helpers.R (comment-aware xvg reader).

out <- list()
for (lig in sys) {
  p1 <- read_pmf(file.path(data_dir, sprintf("sys1_%s_pmf_c1.xvg", lig)))
  p2 <- read_pmf(file.path(data_dir, sprintf("sys1_%s_pmf_c2.xvg", lig)))
  p3 <- read_pmf(file.path(data_dir, sprintf("sys1_%s_pmf_c3.xvg", lig)))
  wd1 <- max(p1$PMF) - min(p1$PMF)
  wd2 <- max(p2$PMF) - min(p2$PMF)
  wd3 <- max(p3$PMF) - min(p3$PMF)
  rc_min_c3 <- p3$RC[which.min(p3$PMF)]
  a <- p2$PMF - min(p2$PMF); b <- p3$PMF - min(p3$PMF)
  r23 <- cor(a, b)
  out[[lig]] <- data.frame(
    ligand = lig, wd_C1 = wd1, wd_C2 = wd2, wd_C3 = wd3,
    wd_mean = mean(c(wd1, wd2, wd3)), wd_sd = sd(c(wd1, wd2, wd3)),
    wd_range = max(c(wd1, wd2, wd3)) - min(c(wd1, wd2, wd3)),
    rc_min_C3 = rc_min_c3, pmf_cor_C2C3 = r23)
}
res <- do.call(rbind, out)

# ---- Asserts against the legacy CSV (full precision, columns that must not drift) ----
legacy <- fread(file.path(data_dir, "cumulant_convergence.csv"))
stopifnot(nrow(legacy) == 7)
for (lig in sys) {
  L <- legacy[ligand == lig]; N <- res[res$ligand == lig, ]
  for (col in c("wd_C1", "wd_C2", "wd_C3", "wd_mean", "wd_sd", "wd_range", "rc_min_C3")) {
    stopifnot(abs(L[[col]] - N[[col]]) < 1e-6)
  }
}
# Recomputed C2-C3 correlations (current PMF files), pinned:
r_expected <- c(APO = 0.9948, AZD5305 = 0.9999, niraparib = 0.9763, olaparib = 0.8888,
                rucaparib = 0.9195, talazoparib = 1.0000, veliparib = 0.8708)
for (lig in sys) {
  stopifnot(abs(res$pmf_cor_C2C3[res$ligand == lig] - r_expected[[lig]]) < 5e-4)
}

write.csv(res, file.path(data_dir, "cumulant_convergence.csv"), row.names = FALSE)
cat("Saved: results/analysis/cumulant_convergence.csv (all asserts passed)\n")
